# testbench
bert_encoder_tb.v
# SRAM behavior model
sram_model/SRAM_activation_4096x128b.v
sram_model/SRAM_weight_16384x128b.v
# non linear model
non_linear_model/softmax.v
non_linear_model/layernorm.v
non_linear_model/GELU.v

# netlist generated by Design Compiler
../../syn/netlist/bert_encoder_syn.v
# Logic Gate models
-v /theda21_2/library/GPDK045/cur/gsclib045/verilog/slow_vdd1v2_basicCells.v

+define+GATESIM
+access+r
